"""add retailer field and unique constraint for name and ratailer

Revision ID: eb1195696f45
Revises: 6037775bba6a
Create Date: 2020-09-23 16:16:04.585357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1195696f45'
down_revision = '6037775bba6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('retailer', sa.String(length=64), nullable=True))
    op.create_unique_constraint('_name_retailer_uc', 'products', ['name', 'retailer'])
    op.drop_index('ix_products_name', table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index('ix_products_name', 'products', ['name'], unique=True)
    op.drop_constraint('_name_retailer_uc', 'products', type_='unique')
    op.drop_column('products', 'retailer')
    # ### end Alembic commands ###
